const TOURNAMENT_SIZE = 50
const RATE_CROSSOVER = 0.2
const RATE_MUTATION_SWAP = 2
const RATE_MUTATION_SUBSTITUTION = 4
const RATE_MUTATION_INSERTION = 3
const RATE_MUTATION_DELETION = 1

const INIT_MAX_CHROMO_SIZE = 5

const MIN_CHROMO_SIZE = 3
const MIN_NO_ROWS = 10

const OVERLAP_PENALTY = 1.2

const EPSILON = .000001

const POPULATION_SIZE = 100
const REPRODUCTION_SIZE = POPULATION_SIZE / 8
const MAX_NUMBER_OF_TABU_HITS = POPULATION_SIZE

const BLOCK_SIZE = 1024

INPUT_PATH = "../data/input/example_input.csv"
OUTPUT_DIR = "data/output"

MAX_ITERATIONS = 2_000
MAX_BICLUSTER_NUMBER = 100
OVERLAP_THRESHOLD = 0.75
APPROX_TRENDS_RATIO = 0.85
NEGATIVE_TRENDS_ENABLED = 1
GPU_NUMBER = 1
