const TOURNAMENT_SIZE = 50
const RATE_CROSSOVER = 0.2
const RATE_MUTATION_SWAP = 2
const RATE_MUTATION_SUBSTITUTION = 4
const RATE_MUTATION_INSERTION = 3
const RATE_MUTATION_DELETION = 1

const INIT_MIN_CHROMO_SIZE = 2
const INIT_MAX_CHROMO_SIZE = 4

const MIN_CHROMO_SIZE = 4

const OVERLAP_PENALTY = 1.2

const EPSILON = .000001

const POPULATION_SIZE = 100
const REPRODUCTION_SIZE = POPULATION_SIZE / 4
const MAX_NUMBER_OF_TABU_HITS = POPULATION_SIZE

const BLOCK_SIZE = 1024

INPUT_PATH = "../data/input/input1.txt"
EXPERT_KNOWLEDGE_PATH = "data/overlap_bic/overlap_0_0"
OUTPUT_DIR = "data/output"

MAX_ITERATIONS = 10
MAX_BICLUSTER_NUMBER = 100
OVERLAP_THRESHOLD =.75
APPROX_TRENDS_RATIO = .85
NEGATIVE_TRENDS_ENABLED = 1
GPU_NUMBER = 1
